# Generated by Django 5.1.5 on 2025-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='session_price',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='session_time',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='tutor',
            name='certificate',
            field=models.FileField(default='', upload_to='certificates/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='education_level',
            field=models.CharField(default='Not Specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='subject_taught',
            field=models.CharField(default='Not Specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_name',
            field=models.CharField(default='Not Specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='tutor',
            table='Tutor',
        ),
    ]
