# Generated by Django 5.1.5 on 2025-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0002_remove_tutor_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='favorite_tutors',
            field=models.ManyToManyField(blank=True, to='additem.tutor'),
        ),
    ]
