# Generated by Django 5.1.5 on 2025-01-30 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0003_parent_favorite_tutors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='favorite_tutors',
        ),
        migrations.AddField(
            model_name='parent',
            name='favorite_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additem.tutor'),
        ),
    ]
