# Generated by Django 5.1.5 on 2025-02-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0004_remove_parent_favorite_tutors_parent_favorite_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='level',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='session_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='Schedule',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('session_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_level', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_slots', models.JSONField(default=list)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.tutor')),
            ],
            options={
                'db_table': 'Classes',
            },
        ),
    ]
