# Generated by Django 5.1.5 on 2025-02-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0005_schedule_capacity_schedule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='class',
            name='session_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
