# Generated by Django 5.1.5 on 2025-02-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0006_class_capacity_alter_class_session_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
