# Generated by Django 5.1.5 on 2025-02-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0007_delete_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('session_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_level', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_slots', models.JSONField(default=list)),
                ('capacity', models.IntegerField(default=1)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.tutor')),
            ],
            options={
                'db_table': 'Classes',
            },
        ),
    ]
