# Generated by Django 5.1.5 on 2025-02-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0008_class'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='additem_classes',
        ),
    ]
