# Generated by Django 5.1.5 on 2025-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0009_alter_class_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time_slots',
            field=models.JSONField(default=dict),
        ),
    ]
