# Generated by Django 5.1.5 on 2025-02-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0010_alter_class_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='favorite_time_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
