# Generated by Django 5.1.5 on 2025-02-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0011_parent_favorite_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='favorite_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additem.class'),
        ),
    ]
