# Generated by Django 5.1.5 on 2025-02-10 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0014_notification_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tutors_list', to='additem.parent')),
                ('selected_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.class')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.tutor')),
            ],
            options={
                'db_table': 'additem_favoriteTutors',
            },
        ),
    ]
