# Generated by Django 5.1.5 on 2025-02-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0015_favoritetutor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='additem_schedule',
        ),
    ]
