# Generated by Django 5.1.5 on 2025-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0017_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritetutor',
            name='weekday',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
