# Generated by Django 5.1.5 on 2025-02-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0018_favoritetutor_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritetutor',
            name='weekday',
        ),
    ]
