# Generated by Django 5.1.5 on 2025-02-10 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0019_remove_favoritetutor_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='additem_payment',
        ),
    ]
