# Generated by Django 5.1.5 on 2025-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0020_payment_payment_date_alter_payment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='session_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
