# Generated by Django 5.1.5 on 2025-02-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0022_remove_payment_payment_date_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('e_wallet', 'E-Wallet')], default='bank_transfer', max_length=20),
        ),
    ]
