# Generated by Django 5.1.5 on 2025-02-11 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0023_payment_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='communication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='user_role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TUTOR', 'Tutor'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='PARENT', max_length=20),
        ),
    ]
