# Generated by Django 5.1.5 on 2025-02-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0003_communication'),
        ('additem', '0024_alter_communication_options_communication_created_at_and_more'),
    ]

    operations = [
    ]
