# Generated by Django 5.1.5 on 2025-02-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0025_merge_20250211_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='sender',
        ),
        migrations.AddField(
            model_name='communication',
            name='user_role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TUTOR', 'Tutor'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='PARENT', max_length=20),
        ),
    ]
