# Generated by Django 5.1.5 on 2025-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0027_alter_communication_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
