# Generated by Django 5.1.5 on 2025-02-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0028_alter_tutor_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='favorite_class',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='favorite_tutor',
        ),
        migrations.AddField(
            model_name='parent',
            name='favorite_class_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='favorite_tutor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='child_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='favorite_time_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject_taught',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='parent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tutor',
            table=None,
        ),
    ]
